// js/changelogData.js

console.log('[ChangelogData] Script execution started.');

/**
 * Changelog data for the Forte Card Previewer.
 */
const changelogData = [
  {
    version: "2.5.0",
    date: "2025-05-23", // Placeholder: Update with actual release date
    title: "UI Overhaul & Dynamic Content Integration",
    isOpen: true,
    changes: [
      {
        title: "Key Features & Enhancements",
        items: [
          "**Modular UI Components:**",
          "ADDED: Header content is now dynamically generated by `layouts/header.js`.",
          "ADDED: Footer content is now dynamically generated by `layouts/footer.js`.",
          "IMPROVED: Centralized UI controls (sidebar toggle, popups, settings) in `js/ui-controls.js`.",
          "**Version & Changelog System:**",
          "ADDED: Dynamic version display in header using this `js/changelogData.js` file.",
          "ADDED: Clickable version badge in header to open a detailed changelog modal.",
          "IMPROVED: Changelog modal with accordion view for different versions and styled keywords for changes.",
          "**Header & Button Enhancements:**",
          "FIXED: 'Info' button correctly positioned to the left of the 'Join Discord' button in the header.",
          "IMPROVED: Styling for header buttons and actions for better consistency with the application theme.",
          "ADDED: 'Settings' button and modal for user-configurable options (e.g., effects toggle).",
          "**General UI/UX:**",
          "IMPROVED: Footer styling for a cleaner, more concise look and better layout.",
          "IMPROVED: Sidebar toggle functionality with state persistence via localStorage.",
          "REMOVED: Hardcoded version number from HTML document title.",
          "IMPROVED: Refined credits popup with detailed acknowledgments for all contributors."
        ],
      },
      {
        title: "Previous Major Updates (Example from v2.0.0)",
        items: [
          "**Revamped Card Search Panel (`EnhancedCardSearchPanel.js`):**",
          "ADDED: Default Load: Displays cards from the latest Pokémon TCG set on initial load for faster startup.",
          "CHANGED: Manual Search Trigger: Card searches are now initiated only by pressing the \"Search\" button.",
          "IMPROVED: Filter Panel Behavior: Search filter accordion now automatically minimizes when a search is executed.",
          "IMPROVED: Card Preview: Clicking a card image in search results now opens an enhanced preview modal (`CardPreviewModal.js`).",
          "ADDED: Custom Set Tabs: Integrated `CustomSetTabs.js` for managing and navigating user-created custom card sets.",
        ],
      },
      {
        title: "Bug Fixes & Stability",
        items: [
          "FIXED: Various minor layout and alignment issues across the application.",
          "IMPROVED: Robustness of modal open/close logic, especially for ESC key handling.",
          "FIXED: Addressed issues with button placement and dynamic content injection.",
        ],
      },
    ],
  },
  {
    version: "2.0.0",
    date: "2025-03-01", 
    title: "Forte Project Fork & Custom Card System",
    isOpen: false, 
    changes: [
      {
        title: "Project Direction & Core Changes",
        items: [
          "NEW: Project forked from 'Pocket-Image-Previewer' to become 'Forte Card Previewer'.",
          "NEW: Shifted focus to support custom 'Forte' card mechanics, Wuthering Waves elements, and a community-driven metagame.",
          "ADDED: Concept of 'Forte Generals' and a collaborative design process for the metagame.",
        ],
      },
      {
        title: "Custom Card & Data Management",
        items: [
          "ADDED: Initial backend integration concepts for card submissions and approvals (e.g., via Google Apps Script and Sheets).",
          "ADDED: `generate_image_structure.js` script for processing card data and images based on a defined naming scheme, including parsing for Forte status, types, creators, etc.",
          "IMPROVED: Data structure in `image_data.js` to include more detailed card attributes and counterpart information (blank/normal versions).",
        ],
      },
      {
        title: "Core Functionality Adaptation",
        items: [
          "IMPROVED: Filtering system adapted to include new card properties like 'Forte Status', 'Creator', and specific 'Trainer Types'.",
          "IMPROVED: Gallery display logic to correctly handle and prioritize normal vs. blank card versions.",
          "MAINTAINED: Core image viewing capabilities, lightbox functionality, and set-based navigation from v1.x, adapted for the new data structure.",
        ],
      },
    ],
  },
  {
    version: "1.0.0",
    date: "2024-10-15",
    title: "Original Pocket Image Previewer",
    isOpen: false,
    changes: [
      {
        title: "Core Image Gallery Features",
        items: [
          "ADDED: Folder-based navigation for image sets with tabbed interface.",
          "ADDED: 'All' tab for recursive loading and display of all images.",
          "ADDED: Filtering by card Type & Rarity parsed from image filenames.",
          "ADDED: Configuration for filters, folder order, and tab colors via `filter_config.json`.",
        ],
      },
      {
        title: "Interactive Elements & UX",
        items: [
          "ADDED: Interactive Holo effect on thumbnails and lightbox images, reacting to mouse/touch.",
          "ADDED: Click effect on thumbnails before opening the lightbox.",
          "ADDED: Dynamic sizing controls (sliders) for gallery thumbnails and lightbox popup size, with settings saved to localStorage.",
          "ADDED: 'Load More' functionality for batched image loading to improve initial performance.",
          "ADDED: Lazy loading for gallery thumbnails.",
        ],
      },
      {
        title: "Multimedia & Aesthetics",
        items: [
          "ADDED: Background audio player with play/pause, next track, and volume controls.",
          "ADDED: Three.js animated particle background for visual flair.",
          "ADDED: Responsive design considerations for usability on different screen sizes.",
        ],
      },
    ],
  }
];

try {
    if (typeof changelogData !== 'undefined' && Array.isArray(changelogData) && changelogData.length > 0) {
        // Set global changelogData
        if (typeof window.changelogData === 'undefined') {
            window.changelogData = changelogData;
        } else {
            console.warn('[ChangelogData] window.changelogData already defined. Overwriting.');
            window.changelogData = changelogData;
        }

        // Set global latestVersion
        const firstEntry = changelogData[0];
        if (firstEntry && typeof firstEntry.version !== 'undefined') {
            if (typeof window.latestVersion === 'undefined') {
                window.latestVersion = firstEntry;
            } else {
                console.warn('[ChangelogData] window.latestVersion already defined. Overwriting.');
                window.latestVersion = firstEntry;
            }
            console.log('[ChangelogData] Changelog data loaded successfully. Latest version:', window.latestVersion.version);
        } else {
            console.error('[ChangelogData] First entry in changelogData is invalid or missing a version property.');
            window.latestVersion = undefined; // Ensure it's undefined if data is bad
        }
    } else {
        console.error('[ChangelogData] changelogData array is undefined, not an array, or empty.');
        window.changelogData = undefined;
        window.latestVersion = undefined;
    }
} catch (error) {
    console.error('[ChangelogData] Error during script execution:', error);
    window.changelogData = undefined;
    window.latestVersion = undefined;
}

console.log('[ChangelogData] Script execution finished.');
